"""add_reminder_sent_at_to_tasks

Revision ID: 5bbbcf1b4ae7
Revises: 79d6152fb55e
Create Date: 2026-03-26 18:01:58.092947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbbcf1b4ae7'
down_revision: Union[str, Sequence[str], None] = '79d6152fb55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reminder_sent_at')
    # ### end Alembic commands ###
