"""add_username_history

Revision ID: 7564e699026b
Revises: 14189401f524
Create Date: 2026-03-28 22:22:29.315029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7564e699026b'
down_revision: Union[str, Sequence[str], None] = '14189401f524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('username_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_username', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_username_history_old_username', 'username_history', ['old_username'], unique=False)
    op.create_index(op.f('ix_username_history_user_id'), 'username_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_username_history_user_id'), table_name='username_history')
    op.drop_index('ix_username_history_old_username', table_name='username_history')
    op.drop_table('username_history')
    # ### end Alembic commands ###
