"""add_comment_mentions_and_task_mentions

Revision ID: 8dd22723e743
Revises: 7564e699026b
Create Date: 2026-03-29 15:31:05.452908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd22723e743'
down_revision: Union[str, Sequence[str], None] = '7564e699026b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_mentions',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_index(op.f('ix_task_mentions_user_id'), 'task_mentions', ['user_id'], unique=False)
    op.create_table('comment_mentions',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_index(op.f('ix_comment_mentions_user_id'), 'comment_mentions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_mentions_user_id'), table_name='comment_mentions')
    op.drop_table('comment_mentions')
    op.drop_index(op.f('ix_task_mentions_user_id'), table_name='task_mentions')
    op.drop_table('task_mentions')
    # ### end Alembic commands ###
