"""add_actor_id_to_mention_tables

Revision ID: aa0d2d5c9831
Revises: 8dd22723e743
Create Date: 2026-03-31 00:27:47.453198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0d2d5c9831'
down_revision: Union[str, Sequence[str], None] = '8dd22723e743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_mentions', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_mentions_actor_id'), 'comment_mentions', ['actor_id'], unique=False)
    op.create_foreign_key(None, 'comment_mentions', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.add_column('task_mentions', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_mentions_actor_id'), 'task_mentions', ['actor_id'], unique=False)
    op.create_foreign_key(None, 'task_mentions', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_mentions', type_='foreignkey')
    op.drop_index(op.f('ix_task_mentions_actor_id'), table_name='task_mentions')
    op.drop_column('task_mentions', 'actor_id')
    op.drop_constraint(None, 'comment_mentions', type_='foreignkey')
    op.drop_index(op.f('ix_comment_mentions_actor_id'), table_name='comment_mentions')
    op.drop_column('comment_mentions', 'actor_id')
    # ### end Alembic commands ###
